### ISSUE TITLE
CLI XML parsing does not support parsing from stream or memory

### ISSUE THREAD

**Issue by zachmullen** [commontk/ctk-cli#10]
The `CLIModule` class supports two modes of XML parsing: passing a path to a CLI executable, or passing the path to an XML file. However, for my use case, I already have an open file-like object containing the XML data, but it is not a file on disk. It would be nice to be able to use ctk_cli's XML parsing without having to write this to disk. Being able to pass this file-like object directly would be ideal, but it would also be fine to allow passing the XML document as a string in memory.

**Comment by zachmullen** [comment]
Alternatively, passing in an `ElementTree` object would also make things easy for my use case.

**Comment by hmeine** [comment]
Good point. Which option would you prefer?

**Comment by zachmullen** [comment]
Passing a file-like object is the most generic and does not rely on exposing ElementTree in the public API, which would be preferable in case we switch parsing implementations, e.g. lxml.

I will go ahead and make a PR for that.

**Comment by hmeine** [comment]
Perfect.  I'd also like to hear about the background of this request.  It is not related to the NAMIC project week, is it?

**Comment by zachmullen** [comment]
Not really related to project week, this is for use in a girder plugin that executes Slicer CLIs on a distributed batch processing cluster. It's a port of some existing functionality in https://github.com/girder/slicer_cli_web and the new work lives here: https://github.com/girder/girder/pull/1693

**Comment by hmeine** [comment]
@zachmullen I just crafted a release (1.4), sorry that it took me a while. Thanks for the PR (and to @jcfr  for the docs stub)!
